ktor:
  application:
    modules:
      - com.music.api.ApplicationKt.module
  deployment:
    port: 8080

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/musicapp"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "fer123"
  maxPoolSize: 10